version: "3"

services:
  webapp-prod:
    container_name: production
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - .env
    ports:
      - 80:80
