name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - run: ls
    - run: touch .env # creating empty env file coz docker compose needs one
    - run: docker build --target test -t todo-app:test . 
    - run: docker run --env-file ./.env.test todo-app:test

  dockerhub:
    name: Build and image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'module-9'
    steps:
    - run: echo "Publishing!"
    - uses: actions/checkout@v2
    - name: docker build
      run: docker build -t zorion75/todo-app .
    - name: login
      run: echo ${{secrets.DOCKER_HUB_TOKEN}} | docker login --username zorion75 --password-stdin
    - name: push image to docker hub
      run: docker push zorion75/todo-app